apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkite-scheduler-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: buildkite-scheduler-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - jobs
      - services
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: buildkite-scheduler-role-nisa-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildkite-scheduler-role
subjects:
  - kind: ServiceAccount
    name: buildkite-scheduler-serviceaccount
    namespace: default